基于 TensorFlow 构建基础的神经网络，来处理 Numpy 生成的随机数据

* 构建图
* 初始化 Session
* 填充数据，并且获取结果

> 📚 参考资料: [Intro-to-Tensorflow-DL/FirstNeuralNetwork](https://github.com/anujdutt9/Tensorflow-DeepLearning/blob/master/Intro-to-Tensorflow-DL/FirstNeuralNetwork.ipynb)


In [0]:
# 导入依赖

import tensorflow as tf
import numpy as np

# 设置随机数
np.random.seed(101)
tf.set_random_seed(101)

[[ 1.51639863  2.51639863]
 [ 1.57066759  2.57066759]]


In [0]:
# 开始创建数据

# 构建随机 5x5 输入矩阵
rand_a = np.random.uniform(0,100,(5,5))

print(rand_a)
print('\n')

# 构建 5x1 输出矩阵
rand_b = np.random.uniform(0,100,(5,1))

print(rand_b)

[[ 51.63986277  57.06675869   2.84742265  17.15216562  68.52769817]
 [ 83.38968626  30.69662197  89.36130797  72.15438618  18.99389542]
 [ 55.42275911  35.2131954   18.18924027  78.56017619  96.54832224]
 [ 23.23536618   8.35614337  60.35484223  72.89927573  27.62388285]
 [ 68.53063288  51.78674742   4.84845374  13.78692376  18.69674261]]


[[ 99.43179012]
 [ 52.06653967]
 [ 57.87895355]
 [ 73.48190583]
 [ 54.19617722]]


In [0]:
# 构建变量与操作
# Placeholders require only data-type and shape (optional)
a = tf.placeholder(tf.float32)
b = tf.placeholder(tf.float32)

# 加法操作
add_op = a + b

# 乘法操作
mul_op = a * b

In [0]:
# 构建 TensorFlow Session 并且运行
with tf.Session() as sess:
    # Pass in values for "a" and "b" using "feed_dict={}"
    add_result = sess.run(add_op,feed_dict={a:rand_a,b:rand_b})
    print(add_result)
    
    print('\n')
    
    multiply_result = sess.run(mul_op,feed_dict={a:rand_a,b:rand_b})
    print(multiply_result)

[[ 151.07165527  156.49855042  102.27921295  116.58396149  167.95948792]
 [ 135.45622253   82.76316071  141.42784119  124.22093201   71.06043243]
 [ 113.30171204   93.09214783   76.06819153  136.43911743  154.42727661]
 [  96.7172699    81.83804321  133.83674622  146.38117981  101.10578918]
 [ 122.72680664  105.98292542   59.04463196   67.98310089   72.89292145]]


[[ 5134.64404297  5674.25         283.12432861  1705.47070312
   6813.83154297]
 [ 4341.8125      1598.26696777  4652.73388672  3756.8293457    988.9463501 ]
 [ 3207.8112793   2038.10290527  1052.77416992  4546.98046875
   5588.11572266]
 [ 1707.37902832   614.02526855  4434.98876953  5356.77734375
   2029.85546875]
 [ 3714.09838867  2806.64379883   262.76763916   747.19854736
   1013.29199219]]


# Forward Propagation | 简单正向神经网络计算

In [0]:
# 输入数据的特征数目
# Number 
features_num = 10

# 隐层中神经元数目
hidden_layer_nodes_num = 3


# 数据集
# Placeholder# Placeh 
# x: Input Data with features = features_num
# Rows: Num Samples
# Cols: Num Features
# Rows Set to None as it depends on batch size i.e. how many samples come under a batch size defined
# X = tf.placeholder(tf.float32, shape=(rows,cols))
X = tf.placeholder(tf.float32, shape=(None,features_num))

print(X)

# Variables
# Variables need to be provided with Initial Values

# Weight, 初始化随机权重
# tf.random_normal(shape): Returns a tensor of the specified shape filled with random normal values.
W = tf.Variable(tf.random_normal(shape=[features_num, hidden_layer_nodes_num]))

print(W)

# 偏移量矩阵
# tf.ones(shape): Returns a tensor of specified shape filled with "1's".
B = tf.Variable(tf.ones(shape=([hidden_layer_nodes_num])))

print(B)

Tensor("Placeholder_5:0", shape=(?, 10), dtype=float32)
Tensor("Variable_2/read:0", shape=(10, 3), dtype=float32)
Tensor("Variable_3/read:0", shape=(3,), dtype=float32)


In [0]:
# 构建神经网络计算图
# Multiplication Operation
XW = tf.matmul(X,W)

print(XW)


# Addition Operation
Z = tf.add(XW,B)

print(Z)

# Activation Function | 激活函数
A = tf.sigmoid(Z)

print(A)

Tensor("MatMul_2:0", shape=(?, 3), dtype=float32)
Tensor("Add_2:0", shape=(?, 3), dtype=float32)
Tensor("Sigmoid_2:0", shape=(?, 3), dtype=float32)


In [0]:
# 本部分计算隐层的输出

# 初始化全局变量
init = tf.global_variables_initializer()

# 执行计算
with tf.Session() as sess:
    sess.run(init)
    
    # Since there is only one Placeholder "x", provide it's value using feed_dict = {} 
    y_hat = sess.run(A, feed_dict={X:np.random.random([19,features_num])})
    
    # y_hat = sess.run(a,feed_dict={x:np.reshape(np.array([1,2,3,4,5,6,7,8,9,10]),[1,10])})
    # [[  7.63079111e-09   3.67266089e-02   1.38135381e-09]]
    # [[  1.00000000e+00   7.07776564e-07   1.00000000e+00]]  
    
    print(y_hat)


[[ 0.26712373  0.82281733  0.66287428]
 [ 0.3545219   0.86869258  0.64629662]
 [ 0.37431616  0.62756479  0.69156104]
 [ 0.22459137  0.91661626  0.68012166]
 [ 0.27398425  0.75885504  0.46602228]
 [ 0.31032524  0.85040402  0.78365159]
 [ 0.42105407  0.92794871  0.39399543]
 [ 0.39582449  0.65977025  0.28165027]
 [ 0.26036012  0.86434674  0.18223025]
 [ 0.49328178  0.94590062  0.71169335]
 [ 0.32906279  0.69143319  0.22855423]
 [ 0.21358487  0.83882916  0.7003904 ]
 [ 0.3553015   0.91573012  0.7346285 ]
 [ 0.28895459  0.89422554  0.75605559]
 [ 0.47909623  0.82952327  0.54410845]
 [ 0.78835404  0.7721023   0.57869256]
 [ 0.33289137  0.83007735  0.27993578]
 [ 0.26893505  0.81677729  0.48114902]
 [ 0.29366079  0.77087712  0.41737509]]


# Simple Regression | 简单拟合